import { validateBlueprint } from "./src/ai/validators/blueprint.validator.js";


// The Blueprint generated by your Meta Architect
const blueprint = {
    "metadata": {
        "id": "RAG_Comparative_Report_Generation",
        "version": "1.0.0",
        "generatedFrom": "Intent Object",
        "complexity": "HIGH"
    },
    "execution": {
        "entryTask": "Define_Selection_Criteria",
        "allowParallel": false,
        "allowLoops": false,
        "maxRetries": 3,
        "maxTasks": 7
    },
    "tasks": [
        {
            "id": "Define_Selection_Criteria",
            "name": "Define Selection Criteria for Top 25 Papers",
            "objective": "Determine the criteria for selecting the top 25 research papers on RAG",
            "rationale": "To ensure the selection of relevant and high-quality papers",
            "capabilities": [
                "Research Paper Analysis",
                "Selection Criteria Definition"
            ],
            "dependencies": [],
            "expectedInput": [
                "Definition of top papers",
                "Time window"
            ],
            "expectedOutput": [
                "Selection criteria"
            ],
            "successCriteria": [
                "Clear definition of selection criteria",
                "Relevant papers selected"
            ]
        },
        {
            "id": "Retrieve_Research_Papers",
            "name": "Retrieve Research Papers on RAG",
            "objective": "Retrieve research papers on RAG based on the defined selection criteria",
            "rationale": "To gather relevant papers for comparative analysis",
            "capabilities": [
                "Research Paper Retrieval",
                "Database Search"
            ],
            "dependencies": [
                "Define_Selection_Criteria"
            ],
            "expectedInput": [
                "Selection criteria"
            ],
            "expectedOutput": [
                "List of research papers"
            ],
            "successCriteria": [
                "Relevant papers retrieved",
                "Papers meet selection criteria"
            ]
        },
        {
            "id": "Extract_Evaluation_Metrics",
            "name": "Extract Evaluation Metrics from Research Papers",
            "objective": "Extract evaluation metrics from the retrieved research papers",
            "rationale": "To compare the performance of different RAG models",
            "capabilities": [
                "Evaluation Metric Extraction",
                "Data Analysis"
            ],
            "dependencies": [
                "Retrieve_Research_Papers"
            ],
            "expectedInput": [
                "List of research papers"
            ],
            "expectedOutput": [
                "Evaluation metrics data"
            ],
            "successCriteria": [
                "Evaluation metrics extracted accurately",
                "Data is consistent"
            ]
        },
        {
            "id": "Perform_Comparative_Analysis",
            "name": "Perform Comparative Analysis of RAG Models",
            "objective": "Perform a comparative analysis of the RAG models based on the extracted evaluation metrics",
            "rationale": "To identify the strengths and weaknesses of different RAG models",
            "capabilities": [
                "Comparative Analysis",
                "Data Visualization"
            ],
            "dependencies": [
                "Extract_Evaluation_Metrics"
            ],
            "expectedInput": [
                "Evaluation metrics data"
            ],
            "expectedOutput": [
                "Comparative analysis report"
            ],
            "successCriteria": [
                "Report is comprehensive and accurate",
                "Insights are meaningful"
            ]
        },
        {
            "id": "Generate_Comprehensive_Report",
            "name": "Generate Comprehensive Comparative Report",
            "objective": "Generate a comprehensive comparative report with citations",
            "rationale": "To provide a detailed and informative report on the comparative analysis of RAG models",
            "capabilities": [
                "Report Generation",
                "Citation Management"
            ],
            "dependencies": [
                "Perform_Comparative_Analysis"
            ],
            "expectedInput": [
                "Comparative analysis report"
            ],
            "expectedOutput": [
                "Comprehensive comparative report with citations"
            ],
            "successCriteria": [
                "Report is well-structured and informative",
                "Citations are accurate and complete"
            ]
        }
    ],
    "edges": [
        {
            "from": "START",
            "to": "Define_Selection_Criteria",
            "condition": "ALWAYS"
        },
        {
            "from": "Define_Selection_Criteria",
            "to": "Retrieve_Research_Papers",
            "condition": "ALWAYS"
        },
        {
            "from": "Retrieve_Research_Papers",
            "to": "Extract_Evaluation_Metrics",
            "condition": "ALWAYS"
        },
        {
            "from": "Extract_Evaluation_Metrics",
            "to": "Perform_Comparative_Analysis",
            "condition": "ALWAYS"
        },
        {
            "from": "Perform_Comparative_Analysis",
            "to": "Generate_Comprehensive_Report",
            "condition": "ALWAYS"
        },
        {
            "from": "Generate_Comprehensive_Report",
            "to": "END",
            "condition": "ALWAYS"
        }
    ],
    "constraints": {
        "requiresVerification": false,
        "allowParallel": false,
        "requiresHumanApproval": false
    },
    "successCriteria": [
        "Report analyzes exactly 25 selected RAG papers published within the last three years",
        "All papers are selected based on documented selection criteria",
        "Evaluation metrics for each paper are extracted and presented without errors",
        "Comparative analysis includes quantitative tables and qualitative insights",
        "Report length is between 10 and 15 pages",
        "All citations follow a consistent academic style and are verifiable",
        "No task fails; each edge executes with SUCCESS condition"
    ],
    "finalOutput": {
        "artifact": "Comprehensive comparative report on Retrieval-Augmented Generation (RAG) research papers with full citations and analysis of evaluation metrics.",
        "format": "PDF document with structured sections, tables, visualizations, and a bibliography"
    }
}

// Execute Validation
const runTest = () => {
    console.log(`[🚀] Starting validation for Blueprint: ${blueprint.metadata.id}...\n`);

    const startTime = performance.now();
    const result = validateBlueprint(blueprint);
    const endTime = performance.now();

    // Strip the full blueprint payload from the terminal output to keep it clean
    const { blueprint: _, ...cleanResult } = result;

    if (result.valid) {
        console.log(`[✅] Validation Passed in ${(endTime - startTime).toFixed(2)}ms`);
        console.log("\n--- Metrics ---");
        console.log(JSON.stringify(cleanResult.metrics, null, 2));
    } else {
        console.log(`[❌] Validation Failed in ${(endTime - startTime).toFixed(2)}ms`);
    }

    if (cleanResult.errors.length > 0) {
        console.log("\n--- Errors ---");
        console.log(JSON.stringify(cleanResult.errors, null, 2));
    }

    if (cleanResult.warnings.length > 0) {
        console.log("\n--- Warnings ---");
        console.log(JSON.stringify(cleanResult.warnings, null, 2));
    }
};

runTest();